baseURL: https://swedenborg.com.au/
languageCode: en-AU
title: Swedenborg Association of Australia
googleAnalytics: UA-XXX-X
disableKinds:
  - RSS
paginate: 6
summaryLength: 20
taxonomies:
  tag: tags
  category: categories
  location: location
menu:
  main:
    - 
      name: home
      url: /
      weight: 1
    - 
      name: events
      url: /events/
      weight: 2
    - 
      name: news
      url: /news/
      weight: 3
    - 
      name: shop
      url: /shop/
      weight: 4
    - 
      name: about
      url: /about/
      weight: 5
    - 
      parent: about
      name: Swedenborg
      url: /emanuel-swedenborg/
      weight: 2
    - 
      parent: about
      name: contact
      url: /contact/
      weight: 1
outputs:
  home:
    - html
    # - json
  section:
    - html
    # - json
params:
  staticURL: http://static.swedenborg.com.au/
  imagesURL: https://res.cloudinary.com/swedenborg/image/upload/
  author: Joe Vandermeer
  description:
    Since 1992, the SAA has been offering useful events, discussions and material about spiritual life and the spiritual world from the unique experiences and writings of Emanuel Swedenborg. Our aim is to help us prepare for richer experiences ahead, and to relate Swedenborg's writings to our lives.
  email: info@swedenborg.com.au
  facebook: https://www.facebook.com/Swedenborg-Association-of-Australia-104862382911851/