baseURL: https://swedenborg.com.au/
languageCode: en-AU
title: Swedendborg Association of Australia
googleAnalytics: UA-XXX-X
disableKinds:
  - RSS
paginate: 3
params:
  staticURL: https://s3-ap-southeast-2.amazonaws.com/swedenborg.com.au/
  imagesURL: https://res.cloudinary.com/swedenborg/image/upload/
  author: Joe Vandermeer
  description:
    SAA offers unprecedented detail about spiritual life and about the spiritual world, described in the unique experiences and writings of Emanuel Swedenborg, hoping this allows us to prepare for richer and more useful experiences ahead. (Est 1992)
  paginate: 10
  email: info@swedenborg.com.au
  facebook: https://www.facebook.com/Swedenborg-Association-of-Australia-104862382911851/
taxonomies:
  tag: tags
  category: categories
  location: location
menu:
  main:
    - 
      name: home
      url: /
      weight: 1
    - 
      name: events
      url: /events/
      weight: 2
    - 
      name: news
      url: /news/
      weight: 3
    - 
      name: shop
      url: /shop/
      weight: 4
    - 
      name: about
      url: /about/
      weight: 5
    - 
      parent: about
      name: Swedenborg
      url: /emanuel-swedenborg/
      weight: 2
    - 
      parent: about
      name: contact
      url: /contact/
      weight: 1
outputs:
  home:
    - html
    # - json
  section:
    - html
    # - json